version: "3"

services:
  myapp:
    image: sellerdb
    ports:
      - 10091:10091
    depends_on:
      - mongodb

  mongodb:
    image: "mongo"
    container_name: "local_mongo"
    ports:
        - '27014:27017'

  myapp1:
    image: sellerapp
    ports:
      - 10090:10090
    depends_on:
      - myapp

  
